trigger:
- main

pool:
  name: Default
  demands:
    - Agent.Name -equals lba-vm2

variables:
  appName: 'my-nodejs-app'
  nodeVersion: '16.x'

steps:

# Show the agent details
- script: |
    echo "Running on agent: $(Agent.Name)"
    echo "Agent OS: $(Agent.OS)"
  displayName: 'Display Agent Info'

# Install specific Node.js version
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install npm dependencies'

# Run tests (optional)
- script: |
    npm test || echo "No tests found"
  displayName: 'Run Tests'

# Start the app (only for testing/demo purposes)
- script: |
    npm start
  displayName: 'Start the App'
