trigger:
- main

pool:
  name: Default   # Self-hosted agent pool

variables:
  appName: 'my-nodejs-app'
  nodeVersion: '16.x'

steps:

# Show the agent details
- script: |
    echo "Running on agent: $(Agent.Name)"
    echo "Agent OS: $(Agent.OS)"
  displayName: 'Display Agent Info'

# Use specific Node.js version
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install
  displayName: 'Install npm dependencies'

# Run tests (optional — only if your app has tests)
- script: |
    npm test || echo "No tests found"
  displayName: 'Run tests'

# Start the app (for test/demo; not recommended for prod)
- script: |
    npm start
  displayName: 'Start Node.js App'
